version: '3.8'
services:
  madness:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    #runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Set to 'none' to disable GPU or specify device IDs
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    container_name: madness
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "22:22"
      - "8888:8888"
    volumes:
      - ./assets:/mnt/assets
      - ./cache:/mnt/cache
      - ./logs:/mnt/logs
      - ./src:/mnt/src
      - ./env:/mnt/env
    command: tail -f /dev/null